use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportSection {
    pub title: String,
    pub content: String,
    pub severity: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PdfReport {
    pub title: String,
    pub target: String,
    pub date: DateTime<Utc>,
    pub summary: String,
    pub executive_summary: String,
    pub sections: Vec<ReportSection>,
    pub total_findings: usize,
    pub critical_count: usize,
    pub high_count: usize,
    pub medium_count: usize,
    pub low_count: usize,
    pub info_count: usize,
    pub report_hash: String,
    pub page_count: usize,
}

impl PdfReport {
    pub fn new(target: String) -> Self {
        Self {
            title: format!("Security Assessment Report — {}", target),
            target,
            date: Utc::now(),
            summary: String::new(),
            executive_summary: String::new(),
            sections: Vec::new(),
            total_findings: 0,
            critical_count: 0,
            high_count: 0,
            medium_count: 0,
            low_count: 0,
            info_count: 0,
            report_hash: String::new(),
            page_count: 0,
        }
    }

    pub fn add_section(&mut self, section: ReportSection) {
        let severity = section.severity.as_deref();
        match severity {
            Some("Critical") => self.critical_count += 1,
            Some("High") => self.high_count += 1,
            Some("Medium") => self.medium_count += 1,
            Some("Low") => self.low_count += 1,
            _ => self.info_count += 1,
        }
        self.total_findings += 1;
        self.sections.push(section);
    }

    pub fn set_summary(&mut self, summary: String) {
        self.summary = summary;
    }

    pub fn set_executive_summary(&mut self, text: String) {
        self.executive_summary = text;
    }

    pub fn generate_hash(&mut self) {
        let input = format!(
            "{}{}{}{}",
            self.title, self.target, self.date, self.total_findings
        );
        let mut hasher = Sha256::new();
        hasher.update(input.as_bytes());
        self.report_hash = hex::encode(hasher.finalize());
    }

    pub fn render_markdown(&self) -> String {
        let mut md = String::new();

        md.push_str(&format!("# {}\n\n", self.title));
        md.push_str(&format!("**Target:** {}\n\n", self.target));
        md.push_str(&format!("**Date:** {}\n\n", self.date.format("%Y-%m-%d %H:%M UTC")));
        md.push_str(&format!("**Report Hash:** `{}`\n\n", self.report_hash));

        md.push_str("## Executive Summary\n\n");
        md.push_str(&self.executive_summary);
        md.push_str("\n\n");

        md.push_str("## Finding Summary\n\n");
        md.push_str("| Severity | Count |\n|----------|-------|\n");
        md.push_str(&format!("| Critical | {} |\n", self.critical_count));
        md.push_str(&format!("| High     | {} |\n", self.high_count));
        md.push_str(&format!("| Medium   | {} |\n", self.medium_count));
        md.push_str(&format!("| Low      | {} |\n", self.low_count));
        md.push_str(&format!("| Info     | {} |\n", self.info_count));
        md.push_str(&format!("| **Total**| **{}** |\n", self.total_findings));
        md.push('\n');

        md.push_str("## Detailed Findings\n\n");
        for (i, section) in self.sections.iter().enumerate() {
            md.push_str(&format!("### {}. {}\n\n", i + 1, section.title));
            if let Some(sev) = &section.severity {
                md.push_str(&format!("**Severity:** {}\n\n", sev));
            }
            md.push_str(&section.content);
            md.push_str("\n\n");
        }

        md.push_str("---\n\n");
        md.push_str(&format!("_Generated by Kraken Security Platform — {}_\n", self.date.format("%Y-%m-%d")));

        md
    }

    pub fn estimate_pages(&self) -> usize {
        let base = 3;
        let sections = self.sections.len();
        let total = base + sections + (self.total_findings / 5);
        total.max(1)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_report() {
        let report = PdfReport::new("192.168.1.1".into());
        assert_eq!(report.target, "192.168.1.1");
        assert!(report.title.contains("192.168.1.1"));
        assert_eq!(report.total_findings, 0);
    }

    #[test]
    fn test_add_section() {
        let mut report = PdfReport::new("example.com".into());
        report.add_section(ReportSection {
            title: "SQL Injection".into(),
            content: "Found in /login.php".into(),
            severity: Some("Critical".into()),
        });
        assert_eq!(report.total_findings, 1);
        assert_eq!(report.critical_count, 1);
    }

    #[test]
    fn test_generate_hash() {
        let mut report = PdfReport::new("test".into());
        report.generate_hash();
        assert_eq!(report.report_hash.len(), 64);
    }

    #[test]
    fn test_render_markdown() {
        let mut report = PdfReport::new("test.local".into());
        report.set_executive_summary("No critical issues.".into());
        report.add_section(ReportSection {
            title: "XSS".into(),
            content: "Reflected XSS in search".into(),
            severity: Some("High".into()),
        });
        report.generate_hash();
        let md = report.render_markdown();
        assert!(md.contains("Executive Summary"));
        assert!(md.contains("XSS"));
        assert!(md.contains("Reflected XSS"));
        assert!(md.contains("test.local"));
    }

    #[test]
    fn test_estimate_pages() {
        let mut report = PdfReport::new("target".into());
        for i in 0..10 {
            report.add_section(ReportSection {
                title: format!("Issue {}", i),
                content: "details".into(),
                severity: Some("Medium".into()),
            });
        }
        assert!(report.estimate_pages() > 3);
    }
}
