use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReportSection {
    pub title: String,
    pub content: String,
    pub severity: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PdfReport {
    pub title: String,
    pub target: String,
    pub date: DateTime<Utc>,
    pub summary: String,
    pub executive_summary: String,
    pub sections: Vec<ReportSection>,
    pub total_findings: usize,
    pub critical_count: usize,
    pub high_count: usize,
    pub medium_count: usize,
    pub low_count: usize,
    pub info_count: usize,
    pub report_hash: String,
    pub page_count: usize,
}

impl PdfReport {
    pub fn new(target: String) -> Self {
        Self {
            title: format!("Security Assessment Report — {}", target),
            target,
            date: Utc::now(),
            summary: String::new(),
            executive_summary: String::new(),
            sections: Vec::new(),
            total_findings: 0,
            critical_count: 0,
            high_count: 0,
            medium_count: 0,
            low_count: 0,
            info_count: 0,
            report_hash: String::new(),
            page_count: 0,
        }
    }

    pub fn add_section(&mut self, section: ReportSection) {
        let severity = section.severity.as_deref();
        match severity {
            Some("Critical") => self.critical_count += 1,
            Some("High") => self.high_count += 1,
            Some("Medium") => self.medium_count += 1,
            Some("Low") => self.low_count += 1,
            _ => self.info_count += 1,
        }
        self.total_findings += 1;
        self.sections.push(section);
    }

    pub fn set_summary(&mut self, summary: String) {
        self.summary = summary;
    }

    pub fn set_executive_summary(&mut self, text: String) {
        self.executive_summary = text;
    }

    pub fn generate_hash(&mut self) {
        let input = format!(
            "{}{}{}{}",
            self.title, self.target, self.date, self.total_findings
        );
        let mut hasher = Sha256::new();
        hasher.update(input.as_bytes());
        self.report_hash = hex::encode(hasher.finalize());
    }

    pub fn render_markdown(&self) -> String {
        let mut md = String::new();

        md.push_str(&format!("# {}\n\n", self.title));
        md.push_str(&format!("**Target:** {}\n\n", self.target));
        md.push_str(&format!("**Date:** {}\n\n", self.date.format("%Y-%m-%d %H:%M UTC")));
        md.push_str(&format!("**Report Hash:** `{}`\n\n", self.report_hash));

        md.push_str("## Executive Summary\n\n");
        md.push_str(&self.executive_summary);
        md.push_str("\n\n");

        md.push_str("## Finding Summary\n\n");
        md.push_str("| Severity | Count |\n|----------|-------|\n");
        md.push_str(&format!("| Critical | {} |\n", self.critical_count));
        md.push_str(&format!("| High     | {} |\n", self.high_count));
        md.push_str(&format!("| Medium   | {} |\n", self.medium_count));
        md.push_str(&format!("| Low      | {} |\n", self.low_count));
        md.push_str(&format!("| Info     | {} |\n", self.info_count));
        md.push_str(&format!("| **Total**| **{}** |\n", self.total_findings));
        md.push('\n');

        md.push_str("## Detailed Findings\n\n");
        for (i, section) in self.sections.iter().enumerate() {
            md.push_str(&format!("### {}. {}\n\n", i + 1, section.title));
            if let Some(sev) = &section.severity {
                md.push_str(&format!("**Severity:** {}\n\n", sev));
            }
            md.push_str(&section.content);
            md.push_str("\n\n");
        }

        md.push_str("---\n\n");
        md.push_str(&format!("_Generated by Kraken Security Platform — {}_\n", self.date.format("%Y-%m-%d")));

        md
    }

    pub fn estimate_pages(&self) -> usize {
        let base = 3;
        let sections = self.sections.len();
        let total = base + sections + (self.total_findings / 5);
        total.max(1)
    }

    pub fn render_html_report(&self) -> String {
        let severity_color = |sev: &str| -> &str {
            match sev {
                "Critical" => "#dc3545",
                "High" => "#fd7e14",
                "Medium" => "#ffc107",
                "Low" => "#0dcaf0",
                _ => "#20c997",
            }
        };

        let mut findings_html = String::new();
        for (i, section) in self.sections.iter().enumerate() {
            let sev = section.severity.as_deref().unwrap_or("Info");
            let color = severity_color(sev);
            findings_html.push_str(&format!(
                r#"<div class="finding">
                    <div class="finding-header">
                        <span class="finding-num">#{}</span>
                        <h3>{}</h3>
                        <span class="severity-badge" style="background:{}">{}</span>
                    </div>
                    <div class="finding-content">{}</div>
                </div>"#,
                i + 1,
                html_escape(&section.title),
                color,
                sev,
                html_escape(&section.content)
            ));
        }

        format!(
            r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{title}</title>
<style>
@media print {{
    body {{ font-size: 10pt; }}
    .no-print {{ display: none; }}
    .finding {{ page-break-inside: avoid; }}
}}
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{ font-family: 'Segoe UI', Arial, sans-serif; color: #333; line-height: 1.6; max-width: 900px; margin: 0 auto; padding: 2rem; }}
.header {{ text-align: center; margin-bottom: 2rem; border-bottom: 3px solid #1a73e8; padding-bottom: 1rem; }}
.header h1 {{ color: #1a73e8; font-size: 1.8rem; }}
.meta {{ display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; margin: 1rem 0; padding: 1rem; background: #f8f9fa; border-radius: 8px; }}
.meta-item {{ font-size: 0.9rem; }}
.meta-item strong {{ color: #555; }}
.summary-grid {{ display: grid; grid-template-columns: repeat(5, 1fr); gap: 0.75rem; margin: 1.5rem 0; }}
.summary-card {{ text-align: center; padding: 1rem; border-radius: 8px; color: white; font-weight: bold; }}
.summary-card .count {{ font-size: 2rem; }}
.summary-card .label {{ font-size: 0.8rem; opacity: 0.9; }}
.executive {{ background: #f0f7ff; border-left: 4px solid #1a73e8; padding: 1.5rem; margin: 1.5rem 0; border-radius: 0 8px 8px 0; }}
.finding {{ border: 1px solid #e0e0e0; border-radius: 8px; margin: 1rem 0; overflow: hidden; }}
.finding-header {{ display: flex; align-items: center; gap: 0.75rem; padding: 0.75rem 1rem; background: #f8f9fa; }}
.finding-num {{ color: #888; font-weight: bold; }}
.finding-header h3 {{ flex: 1; font-size: 1rem; }}
.severity-badge {{ padding: 0.2rem 0.75rem; border-radius: 4px; color: white; font-size: 0.8rem; font-weight: 600; }}
.finding-content {{ padding: 1rem; font-size: 0.9rem; }}
.footer {{ text-align: center; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #ddd; color: #888; font-size: 0.85rem; }}
</style>
</head>
<body>
<div class="header">
    <h1>{title}</h1>
    <p>Security Assessment Report</p>
</div>
<div class="meta">
    <div class="meta-item"><strong>Target:</strong> {target}</div>
    <div class="meta-item"><strong>Date:</strong> {date}</div>
    <div class="meta-item"><strong>Total Findings:</strong> {total}</div>
    <div class="meta-item"><strong>Report Hash:</strong> <code>{hash}</code></div>
</div>
<div class="summary-grid">
    <div class="summary-card" style="background:#dc3545"><div class="count">{critical}</div><div class="label">Critical</div></div>
    <div class="summary-card" style="background:#fd7e14"><div class="count">{high}</div><div class="label">High</div></div>
    <div class="summary-card" style="background:#ffc107;color:#333"><div class="count">{medium}</div><div class="label">Medium</div></div>
    <div class="summary-card" style="background:#0dcaf0;color:#333"><div class="count">{low}</div><div class="label">Low</div></div>
    <div class="summary-card" style="background:#20c997;color:#333"><div class="count">{info}</div><div class="label">Info</div></div>
</div>
<div class="executive">
    <h2>Executive Summary</h2>
    <p>{exec_summary}</p>
</div>
<h2>Detailed Findings</h2>
{findings}
<div class="footer">
    Generated by Kraken Security Platform — {date}
</div>
</body>
</html>"#,
            title = html_escape(&self.title),
            target = html_escape(&self.target),
            date = self.date.format("%Y-%m-%d %H:%M UTC"),
            total = self.total_findings,
            hash = &self.report_hash[..16],
            critical = self.critical_count,
            high = self.high_count,
            medium = self.medium_count,
            low = self.low_count,
            info = self.info_count,
            exec_summary = html_escape(&self.executive_summary),
            findings = findings_html,
        )
    }

    pub fn to_json_report(&self) -> String {
        serde_json::to_string_pretty(self).unwrap_or_default()
    }
}

fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_new_report() {
        let report = PdfReport::new("192.168.1.1".into());
        assert_eq!(report.target, "192.168.1.1");
        assert!(report.title.contains("192.168.1.1"));
        assert_eq!(report.total_findings, 0);
    }

    #[test]
    fn test_add_section() {
        let mut report = PdfReport::new("example.com".into());
        report.add_section(ReportSection {
            title: "SQL Injection".into(),
            content: "Found in /login.php".into(),
            severity: Some("Critical".into()),
        });
        assert_eq!(report.total_findings, 1);
        assert_eq!(report.critical_count, 1);
    }

    #[test]
    fn test_generate_hash() {
        let mut report = PdfReport::new("test".into());
        report.generate_hash();
        assert_eq!(report.report_hash.len(), 64);
    }

    #[test]
    fn test_render_markdown() {
        let mut report = PdfReport::new("test.local".into());
        report.set_executive_summary("No critical issues.".into());
        report.add_section(ReportSection {
            title: "XSS".into(),
            content: "Reflected XSS in search".into(),
            severity: Some("High".into()),
        });
        report.generate_hash();
        let md = report.render_markdown();
        assert!(md.contains("Executive Summary"));
        assert!(md.contains("XSS"));
        assert!(md.contains("Reflected XSS"));
        assert!(md.contains("test.local"));
    }

    #[test]
    fn test_estimate_pages() {
        let mut report = PdfReport::new("target".into());
        for i in 0..10 {
            report.add_section(ReportSection {
                title: format!("Issue {}", i),
                content: "details".into(),
                severity: Some("Medium".into()),
            });
        }
        assert!(report.estimate_pages() > 3);
    }
}
