version: 2
updates:
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Caracas
    labels:
      - dependencies
    commit-message:
      prefix: chore
      include: scope
    groups:
      rust-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Caracas
    labels:
      - ci
    commit-message:
      prefix: ci
