use crate::{DiscoveryMethod, Finding, FindingStatus, Language, Severity};
use chrono::Utc;
use std::path::Path;
use std::process::Command;

pub struct FuzzGuide;

impl FuzzGuide {
    /// Suggests fuzz targets from source code by finding parse/decode/read functions and unsafe blocks.
    ///
    /// # Examples
    ///
    /// ```
    /// use vulnscan::fuzz::FuzzGuide;
    /// use vulnscan::Language;
    /// use std::path::Path;
    /// let code = "fn parse_header(data: &[u8]) -> Header {\n    unsafe { /* ... */ }\n}";
    /// let targets = FuzzGuide::suggest_targets(code, Path::new("parser.rs"), Language::Rust);
    /// assert!(!targets.is_empty());
    /// ```
    pub fn suggest_targets(content: &str, file_path: &Path, _language: Language) -> Vec<String> {
        let mut targets = Vec::new();
        for (i, line) in content.lines().enumerate() {
            let trimmed = line.trim();
            if trimmed.starts_with("fn ")
                && (trimmed.contains("parse")
                    || trimmed.contains("decode")
                    || trimmed.contains("recv")
                    || trimmed.contains("read"))
            {
                targets.push(format!("{}:{}", file_path.display(), i + 1));
            }
            if trimmed.contains("unsafe") {
                targets.push(format!(
                    "{}:{} — contains unsafe block (fuzz target)",
                    file_path.display(),
                    i + 1
                ));
            }
        }
        targets
    }

    /// Generates a cargo-fuzz target template for the given function.
    ///
    /// # Examples
    ///
    /// ```
    /// use vulnscan::fuzz::FuzzGuide;
    /// use std::path::Path;
    /// let template = FuzzGuide::generate_fuzz_target(Path::new("src/parser.rs"), "parse_input");
    /// assert!(template.contains("parse_input"));
    /// assert!(template.contains("fuzz_target"));
    /// ```
    pub fn generate_fuzz_target(file_path: &Path, function_name: &str) -> String {
        let file_stem = file_path
            .file_stem()
            .map(|s| s.to_string_lossy())
            .unwrap_or_default();
        let crate_name = file_path
            .parent()
            .and_then(|p| p.file_name())
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_else(|| "target_crate".to_string());
        format!(
            r#"// Fuzz target for {function_name} in {file_stem}
// Generated by kraken vulnscan
//
// Setup:
//   cargo install cargo-fuzz
//   cargo fuzz init
//   cp this file fuzz/fuzz_targets/{file_stem}_{function_name}.rs
//   cargo fuzz run {file_stem}_{function_name}
#![no_main]

use libfuzzer_sys::fuzz_target;
use std::panic;

fuzz_target!(|data: &[u8]| {{
    // Convert fuzzed bytes to string for text-parsing functions
    if let Ok(input) = std::str::from_utf8(data) {{
        // Catch panics to avoid fuzzer abort on assertion failures
        let _ = panic::catch_unwind(|| {{
            {crate_name}::{function_name}(input);
        }});
    }}
}});
"#,
            function_name = function_name,
            file_stem = file_stem,
            crate_name = crate_name,
        )
    }

    pub fn run_cargo_fuzz(target_dir: &Path, duration_secs: u64) -> Vec<Finding> {
        let mut findings = Vec::new();
        let output = Command::new("cargo")
            .args([
                "fuzz",
                "run",
                "target",
                "--",
                &format!("-max_total_time={}", duration_secs),
            ])
            .current_dir(target_dir)
            .output();

        if let Ok(output) = output {
            let stderr = String::from_utf8_lossy(&output.stderr);
            if stderr.contains("CRASH") || stderr.contains("SUMMARY:") {
                findings.push(Finding {
                    id: crate::new_finding_id(),
                    severity: Severity::High,
                    cwe: Some("CWE-20".to_string()),
                    cve: None,
                    description: "Fuzzer found a crash — potential security vulnerability"
                        .to_string(),
                    file_path: Some(target_dir.to_path_buf()),
                    line_number: None,
                    vulnerable_code_snippet: Some(
                        stderr
                            .lines()
                            .filter(|l| l.contains("CRASH"))
                            .collect::<Vec<_>>()
                            .join("\n"),
                    ),
                    remediation: Some("Inspect the crash and fix the underlying bug".to_string()),
                    confidence: 0.9,
                    discovery_method: DiscoveryMethod::Fuzzing,
                    exploit_code: None,
                    exploit_type: None,
                    chained_findings: vec![],
                    poc_validated: false,
                    status: FindingStatus::Open,
                    cvss_score: Some(7.0),
                    severity_confidence: 0.9,
                    discovered_at: Utc::now(),
                    disclosed: false,
                    disclosure_hash: None,
                });
            }
        }
        findings
    }
}
