use crate::{DiscoveryMethod, Finding, FindingStatus, Language, Severity};
use chrono::Utc;
use std::path::Path;
use std::process::Command;

pub struct FuzzGuide;

impl FuzzGuide {
    pub fn suggest_targets(content: &str, file_path: &Path, _language: Language) -> Vec<String> {
        let mut targets = Vec::new();
        for (i, line) in content.lines().enumerate() {
            let trimmed = line.trim();
            if trimmed.starts_with("fn ")
                && (trimmed.contains("parse")
                    || trimmed.contains("decode")
                    || trimmed.contains("recv")
                    || trimmed.contains("read"))
            {
                targets.push(format!("{}:{}", file_path.display(), i + 1));
            }
            if trimmed.contains("unsafe") {
                targets.push(format!(
                    "{}:{} — contains unsafe block (fuzz target)",
                    file_path.display(),
                    i + 1
                ));
            }
        }
        targets
    }

    pub fn generate_fuzz_target(file_path: &Path, function_name: &str) -> String {
        let file_stem = file_path
            .file_stem()
            .map(|s| s.to_string_lossy())
            .unwrap_or_default();
        format!(
            r#"// Fuzz target for {function_name} in {file_stem}
// Generated by kraken vulnscan
#![no_main]

use libfuzzer_sys::fuzz_target;

fuzz_target!(|data: &[byte]| {{
    // TODO: call {function_name} with fuzzed input
    let _ = data;
}});
"#,
            function_name = function_name,
            file_stem = file_stem,
        )
    }

    pub fn run_cargo_fuzz(target_dir: &Path, duration_secs: u64) -> Vec<Finding> {
        let mut findings = Vec::new();
        let output = Command::new("cargo")
            .args(&[
                "fuzz",
                "run",
                "target",
                "--",
                &format!("-max_total_time={}", duration_secs),
            ])
            .current_dir(target_dir)
            .output();

        if let Ok(output) = output {
            let stderr = String::from_utf8_lossy(&output.stderr);
            if stderr.contains("CRASH") || stderr.contains("SUMMARY:") {
                findings.push(Finding {
                    id: crate::new_finding_id(),
                    severity: Severity::High,
                    cwe: Some("CWE-20".to_string()),
                    cve: None,
                    description: "Fuzzer found a crash — potential security vulnerability"
                        .to_string(),
                    file_path: Some(target_dir.to_path_buf()),
                    line_number: None,
                    vulnerable_code_snippet: Some(
                        stderr
                            .lines()
                            .filter(|l| l.contains("CRASH"))
                            .collect::<Vec<_>>()
                            .join("\n"),
                    ),
                    remediation: Some("Inspect the crash and fix the underlying bug".to_string()),
                    confidence: 0.9,
                    discovery_method: DiscoveryMethod::Fuzzing,
                    exploit_code: None,
                    exploit_type: None,
                    chained_findings: vec![],
                    poc_validated: false,
                    status: FindingStatus::Open,
                    cvss_score: Some(7.0),
                    severity_confidence: 0.9,
                    discovered_at: Utc::now(),
                    disclosed: false,
                    disclosure_hash: None,
                    ..Default::default()
                });
            }
        }
        findings
    }
}
