#!/usr/bin/env bash
set -euo pipefail

# Vendor critical dependencies for offline/air-gapped builds
# These dependencies are vendored because:
# - They are critical for security (no safe Rust alternative)
# - They use unsafe code that needs auditing
# - They must be available for air-gapped deployments
#
# Vendored crates:
# - ring 0.17.x — Cryptographic primitives (C/asm, no pure Rust alt)
# - rustls 0.23.x — TLS (pure Rust, but vendored for audit)
# - hickory-resolver — DNS (pure Rust, vendored for audit)

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
RUST_DIR="${PROJECT_ROOT}/rust"
VENDOR_DIR="${RUST_DIR}/vendor"

echo "=== Kraken Dependency Vendor ==="
echo "Vendor directory: ${VENDOR_DIR}"

cd "${RUST_DIR}"

if [ -d "${VENDOR_DIR}" ]; then
    echo "Vendor directory already exists. Updating..."
else
    echo "Creating vendor directory..."
    mkdir -p "${VENDOR_DIR}"
fi

# Use cargo vendor to fetch all dependencies
echo ""
echo "Running cargo vendor..."
cargo vendor "${VENDOR_DIR}" --respect-config-file

# Configure cargo to use vendored deps
cat > "${RUST_DIR}/.cargo/config.toml" << 'EOCARGO'
# Kraken vendored dependencies configuration
# Generated by scripts/vendor-deps.sh
#
# This configuration allows offline/air-gapped builds
# by using vendored sources instead of fetching from crates.io.

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"
EOCARGO

echo ""
echo "Vendoring complete."
echo ""
echo "Vendored dependencies:"
ls -d "${VENDOR_DIR}"/*/ 2>/dev/null | head -20 || echo "(empty)"
echo ""
echo "Cargo config written to: ${RUST_DIR}/.cargo/config.toml"
echo ""
echo "To build offline: cd rust && cargo build"
echo "To update vendored deps: ./scripts/vendor-deps.sh"
